# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
 adapter:  postgresql
 host:     localhost
 encoding: unicode
 database: deonations_development
 pool:     5
 template: template0

test:
 adapter:  postgresql
 host:     localhost
 encoding: unicode
 database: donations_test
 pool:     5
 template: template0

production:
 adapter:  postgresql
 host:     localhost
 encoding: unicode
 database: donations_production
 pool:     5
 template: template0
